# Generated by Django 3.1 on 2020-10-15 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmbre_dprtmnto', models.CharField(max_length=150, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dscrpcn_gnro', models.CharField(max_length=50, verbose_name='Genero')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dscrpcn_tpo_idntfcn', models.CharField(max_length=150, verbose_name='Tipo de identificación')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='lngtd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lttd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nmro_idntfccn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tlfno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HistorialUbicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hra', models.DateTimeField(max_length=150)),
                ('lngtd', models.IntegerField()),
                ('lttd', models.IntegerField()),
                ('nmro_unco_idntfccn_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmbre_cdd', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('cnsctvo_dprtmnto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='nmro_unco_idntfccn_gnro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.genero'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nmro_unco_idntfccn_tpo_idntfccn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.tipoidentificacion'),
        ),
    ]
