# Generated by Django 3.1.1 on 2020-09-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20200918_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'ordering': ['id'], 'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['id'], 'verbose_name': 'Chat'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['id'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='informe',
            options={'ordering': ['id'], 'verbose_name': 'Informe'},
        ),
        migrations.AlterModelOptions(
            name='localizacion',
            options={'ordering': ['id'], 'verbose_name': 'Localizacion'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['id'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='administrador',
            name='fecha_registro',
            field=models.DateTimeField(max_length=150, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='nro_documento',
            field=models.CharField(max_length=150, unique=True, verbose_name='Número del documento'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nro_documento',
            field=models.CharField(max_length=150, unique=True, verbose_name='Número del documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nro_documento',
            field=models.CharField(max_length=150, unique=True, verbose_name='Número del documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(max_length=150, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nro_documento',
            field=models.CharField(max_length=150, unique=True, verbose_name='Número del documento'),
        ),
    ]
