# Generated by Django 3.1 on 2020-10-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20201005_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
