# Generated by Django 3.1.2 on 2020-12-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20201208_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(max_length=50, null=True, verbose_name='Genero de usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(max_length=50, null=True, verbose_name='Rol de usuario'),
        ),
    ]
