# Generated by Django 3.1.2 on 2020-12-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20201208_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='lngtd',
            field=models.CharField(max_length=50, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lttd',
            field=models.CharField(max_length=50, null=True, verbose_name='Latitud'),
        ),
    ]
