# Generated by Django 3.1.1 on 2020-09-07 22:00

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('nroDocumento', models.CharField(max_length=150, verbose_name='Número del documento')),
                ('celular', models.CharField(max_length=150, verbose_name='Celular')),
                ('fechaDeRegistro', models.DateTimeField(max_length=150, verbose_name='Fecha de registro')),
                ('genero', models.CharField(max_length=150, verbose_name='Genero')),
                ('contagiado', models.BooleanField(max_length=150, verbose_name='Contagiado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'ordering': [builtins.id],
            },
        ),
    ]
