# Generated by Django 3.1.1 on 2020-09-18 21:24

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('nro_documento', models.CharField(max_length=150, verbose_name='Número del documento')),
                ('celular', models.CharField(max_length=150, verbose_name='Celular')),
                ('fecha_registro', models.DateTimeField(max_length=150, verbose_name='Fecha de registro')),
                ('genero', models.CharField(max_length=150, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_chat', models.DateTimeField(max_length=30, verbose_name='Fecha del chat')),
                ('hora_chat', models.TimeField(max_length=30, verbose_name='Hora del chat')),
            ],
            options={
                'verbose_name': 'Chat',
                'db_table': 'chat',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_informe', models.DateTimeField(max_length=30, verbose_name='Fecha del informe')),
                ('hora_informe', models.TimeField(max_length=30, verbose_name='Hora del informe')),
            ],
            options={
                'verbose_name': 'Informe',
                'db_table': 'informe',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_localizacion', models.DateTimeField(max_length=30, verbose_name='Fecha de localización')),
                ('hora_localizacion', models.TimeField(max_length=30, verbose_name='Hora de localización')),
            ],
            options={
                'verbose_name': 'Localizacion',
                'db_table': 'localizacion',
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('nro_documento', models.CharField(max_length=150, verbose_name='Número del documento')),
                ('celular', models.CharField(max_length=150, verbose_name='Celular')),
                ('fecha_registro', models.DateTimeField(max_length=150, verbose_name='Fecha de registro')),
                ('genero', models.CharField(max_length=150, verbose_name='Genero')),
                ('tipo', models.CharField(max_length=15, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': [builtins.id],
            },
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='celular',
            new_name='nro_celular',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='nroDocumento',
            new_name='nro_documento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fechaDeRegistro',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nroDocumento',
            new_name='nro_documento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='localizacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.paciente'),
        ),
        migrations.AddField(
            model_name='informe',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.paciente'),
        ),
        migrations.AddField(
            model_name='chat',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.doctor'),
        ),
        migrations.AddField(
            model_name='chat',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.paciente'),
        ),
    ]
