# Generated by Django 3.1 on 2020-10-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20200922_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(max_length=150, verbose_name='Especialidad'),
        ),
    ]
